name: learning
description: The easy way to use Machine Learning Kit in Flutter.
version: 0.0.1
# author: Salman S
homepage: https://github.com/salkuadrat/learning
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  learning_input_image: ^0.0.3
  learning_language: ^0.0.1
  learning_translate: ^0.0.1
  learning_smart_reply: ^0.0.1+1
  learning_entity_extraction: ^0.0.1+1
  learning_text_recognition: 
    path: packages/learning_text_recognition
  learning_face_detection: 
    path: packages/learning_face_detection

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.salkuadrat.learning
        pluginClass: LearningPlugin
      ios:
        pluginClass: LearningPlugin
