name: learning_object_detection
description: The easy way to use ML Kit for object detection & tracking in Flutter.
version: 0.0.1
# author: Salman S
homepage: https://github.com/salkuadrat/learning/packages/learning_object_detection
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  learning_input_image:
    path: ../learning_input_image

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.salkuadrat.learning.learning_object_detection
        pluginClass: LearningObjectDetectionPlugin
      ios:
        pluginClass: LearningObjectDetectionPlugin
