name: learning_barcode_scanning
description: The easy way to use ML Kit for barcode scanning in Flutter.
version: 0.0.1
# author: Salman S
homepage: https://github.com/salkuadrat/learning/tree/master/packages/learning_barcode_scanning
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  learning_input_image:
    path: ../learning_input_image

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.salkuadrat.learning.learning_barcode_scanning
        pluginClass: LearningBarcodeScanningPlugin
      ios:
        pluginClass: LearningBarcodeScanningPlugin
